# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: anystrom <anystrom@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/01/28 15:50:14 by anystrom          #+#    #+#              #
#    Updated: 2020/01/28 15:53:22 by anystrom         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc chess.c mov.c -o chess
	gcc brackets.c -o brackets

clean:
	rm chess
	rm brackets